"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var cliente_1 = __importDefault(require("./cliente"));
var produto_1 = __importDefault(require("./produto"));
var venda_1 = __importDefault(require("./venda"));
var endereco_1 = __importDefault(require("./endereco"));
var telefone_1 = __importDefault(require("./telefone"));
var endereco1 = new endereco_1.default("Rua Teste", 123, "Cidade", "Estado");
var telefone1 = new telefone_1.default("(00)", 900000000, "Celular");
var telefone2 = new telefone_1.default("(00)", 900000000, "Fixo");
var telefones = [telefone1, telefone2];
var cliente1 = new cliente_1.default("Fulano de Tal", 12345678910, 10101990, endereco1, telefones);
var produto1 = new produto_1.default(10, "Descricao do produto 1", 99.99);
var produto2 = new produto_1.default(20, "Descricao do produto 2", 25.90);
var produtos = [produto1, produto2];
var venda1 = new venda_1.default(1, 29032025, cliente1, produtos);
console.log(venda1);
